// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ConditionType   *string           `json:",omitempty"`
	Condition       *string           `json:",omitempty"`
	PolicyId        *string           `json:",omitempty"`
	Id              *string           `json:",omitempty"`
	EntityGuid      *string           `json:",omitempty"`
	ListQueryFilter *string           `json:",omitempty"`
	Variables       map[string]string `json:",omitempty"`
	Tags            map[string]string `json:",omitempty"`
}
